<?php
/*** @package 	Bookpro* @author 		Ngo Van Quan* @link 		http://joombooking.com* @copyright 	Copyright (C) 2011 - 2012 Ngo Van Quan* @license 	GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html* @version 	$Id: default.php 63 2012-07-29 10:43:08Z quannv $* */
defined ( '_JEXEC' ) or die ( 'Restricted access' );

/* @var $this BookingViewReservations */

JHTML::_ ( 'behavior.tooltip' );
$bar = JToolBar::getInstance ( 'toolbar' );
BookProHelper::setSubmenu ( 4 );
JToolBarHelper::title ( JText::_ ( 'COM_BOOKPRO_AGENT_MANAGER' ), 'user' );
$viewAgent = JText::_ ( 'COM_BOOKPRO_AGENTS_VIEW_AGENT_DETAIL' );
$itemsCount = count ( $this->items );
$pagination = &$this->pagination;
$listOrder = $this->escape ( $this->state->get ( 'list.ordering' ) );
$listDirn = $this->escape ( $this->state->get ( 'list.direction' ) );
?><div class="span10">	<form action="index.php" method="post" name="adminForm" id="adminForm">		<table class="table table-stripped">			<thead>				<tr>					<th width="1%" class="hidden-phone"><?php echo JHtml::_('grid.checkall'); ?>					</th>					<th width="5%"><?php echo JText::_('COM_BOOKPRO_AGENT_STATUS'); ?></th>					<th class="title" width="10%"><?php echo JHTML::_('grid.sort', JText::_('COM_BOOKPRO_AGENT_NAME'), 'name', $listDirn, $listOrder); ?>					</th>					<th width="4%"><?php echo JText::_('COM_BOOKPRO_AGENT_USERNAME'); ?></th>					<th width="4%"><?php echo JText::_('COM_BOOKPRO_AGENT_EMAIL'); ?></th>					<th width="8%"><?php echo JText::_('COM_BOOKPRO_AGENT_PHONE'); ?></th>					<th width="10%"><?php echo JText::_('COM_BOOKPRO_AGENT_FAX'); ?>					</th>					<th width="10%"><?php echo JHTML::_('grid.sort', JText::_('COM_BOOKPRO_AGENT_CREATED_DATE'), 'created', $listDirn, $listOrder); ?>					</th>				</tr>			</thead>			<tfoot>				<tr>					<td colspan="10"><?php echo $pagination->getListFooter(); ?>					</td>				</tr>			</tfoot>			<tbody>				<?php if (!is_array($this->items) || !$itemsCount) { ?>				<tr>					<td colspan="8"><?php echo JText::_('COM_BOOKPRO_AGENT_NO_ITEMS_FOUND.'); ?>					</td>				</tr>				<?php } else { ?>				<?php for ($i = 0; $i < $itemsCount; $i++) { ?>				<?php $subject = &$this->items[$i]; ?>				<tr class="row<?php echo ($i % 2); ?>">					<td class="checkboxCell"><?php echo JHTML::_('grid.checkedout', $subject, $i); ?>					</td>										<td class="center"><?php echo JHtml::_('jgrid.published', $subject->state, $i, 'agents.', true, 'cb', null, null); ?>					</td>					<td><a						href="<?php  echo JRoute::_('index.php?option=com_bookpro&amp;task=agent.edit&amp;id='.$subject->id) ?>">							<?php echo $subject->company; ?>					</a></td>					<td ><?php echo $subject->username; ?>&nbsp;</td>					<td ><?php echo $subject->email; ?>&nbsp;</td>					<td><?php echo $subject->telephone; ?>&nbsp;</td>					<td><?php echo $subject->fax; ?>&nbsp;</td>					<td><?php echo $subject->created; ?>&nbsp;</td>				</tr>				<?php } ?>				<?php } ?>			</tbody>		</table>		<input type="hidden" name="option" value="<?php echo OPTION; ?>" />		<input type="hidden" name="task"			value="<?php echo JRequest::getCmd('task'); ?>" />				<input type="hidden" name="reset" value="0" /> <input type="hidden"			name="controller" value="<?php echo CONTROLLER_AGENT; ?>" /> <input			type="hidden" name="boxchecked" value="0" /> <input type="hidden"			name="filter_order" value="<?php echo $order; ?>" /> <input			type="hidden" name="filter_order_Dir"			value="<?php echo $orderDir; ?>" /> 		<?php echo JHTML::_('form.token'); ?>	</form></div>